apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: meb-moversapp-co-tls
  namespace: cert-manager
spec:
  secretName: meb-moversapp-co
  issuerRef:
    name: letsencrypt-prod
  commonName: meb.moversapp.co
  dnsNames:
    - meb.moversapp.co
