apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: meb-moversapp-co-tls
spec:
  secretName: meb-moversapp-co
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: meb.moversapp.co
  dnsNames:
    - meb.moversapp.co
acme:
  config:
    - http01:
        ingressClass: nginx
      domains:
        - meb.moversapp.co
