apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: jdiaz740/meb-auth
          startupProbe:
            httpGet:
              path: /api/users/healthz
              port: 3000
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/users/healthz
              port: 3000
            initialDelaySeconds: 3
            failureThreshold: 10
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /api/users/healthz
              port: 3000
            initialDelaySeconds: 3
            failureThreshold: 10
            periodSeconds: 3
          env:
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: meb-nats
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth'
            - name: SPACES_ENDPOINT
              value: 'sfo3.digitaloceanspaces.com'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: SPACES_KEY
              valueFrom:
                secretKeyRef:
                  name: spaces-key
                  key: SPACES_KEY
            - name: SPACES_SECRET
              valueFrom:
                secretKeyRef:
                  name: spaces-secret
                  key: SPACES_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
