apiVersion: apps/v1
kind: Deployment
metadata:
  name: clients-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clients
  template:
    metadata:
      labels:
        app: clients
    spec:
      containers:
        - name: clients
          image: jdiaz740/meb-clients
          startupProbe:
            httpGet:
              path: /api/clients/healthz
              port: 3000
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/clients/healthz
              port: 3000
            initialDelaySeconds: 3
            failureThreshold: 10
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /api/clients/healthz
              port: 3000
            initialDelaySeconds: 3
            failureThreshold: 10
            periodSeconds: 3
          env:
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: meb-nats
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: 'mongodb://clients-mongo-srv:27017/clients'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: clients-srv
spec:
  selector:
    app: clients
  ports:
    - name: clients
      protocol: TCP
      port: 3000
      targetPort: 3000
