apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - name: notifications
          image: jdiaz740/meb-notifications
          startupProbe:
            httpGet:
              path: /api/notifications/healthz
              port: 3000
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/notifications/healthz
              port: 3000
            initialDelaySeconds: 3
            failureThreshold: 10
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /api/notifications/healthz
              port: 3000
            initialDelaySeconds: 3
            failureThreshold: 10
            periodSeconds: 3
          env:
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: meb-nats
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: 'mongodb://notifications-mongo-srv:27017/notifications'
            - name: NEW_EMAIL_USERNAME
              value: 'servicioalcliente@mejorenbici.com'
            - name: NEW_EMAIL_PASSWORD
              value: 'nfcuaduptdcanxnm'
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-srv
spec:
  selector:
    app: notifications
  ports:
    - name: notifications
      protocol: TCP
      port: 3000
      targetPort: 3000
