name: tests-travels

on:
  pull_request:
    paths:
      - 'travels/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install && npm run test:ci
        working-directory: travels
